name: destroy

on:
  workflow_dispatch:
    inputs: 
      region:
        description: "Enter the region to destroy : "
        required: true  
        type: string 
        default: "ap-south-1"

env:
  BUCKET: npneeraj-bkt
  TFSTATE_FILE: terraform.tfstate
  aws_region: ${{ github.event.inputs.region }}

jobs:
  destroy_bucket:
    name: destroy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: module
    steps:
      - name: CheckOut
        uses: actions/checkout@v4
      
      - name: set up terraform hashicorp
        uses: hashicorp/setup-terraform@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.aws_region }}
  
      - name: terraform init
        run: terraform init -reconfigure -backend-config="bucket=${{ env.BUCKET }}" -backend-config="key=${{ env.TFSTATE_FILE }}" -backend-config="region=${{ env.aws_region }}"
        
      - name: destroy
        run: terraform destroy -auto-approve
